version: '3.4'

services:

  frontend:
    image: a10d/pa_web1_frontend
    build:
      context: frontend
      args:
        BACKEND_CONNECTOR: server
        BACKEND_URL: http://localhost:8080/
    ports:
      - "5173:80"

  backend:
    image: a10d/pa_web1_backend
    build:
      context: backend
    ports:
      - "8080:8080"
    environment:
      - APP_INTERFACE=:8080
