version: '3.4'

services:
  frontend:
    image: a10d/pa_web1_frontend
    build:
      context: frontend
    ports:
      - "8081:80"
    environment:
      - VITE_BACKEND_CONNECTOR=server
      - VITE_BACKEND_URL=http://localhost:8090
  backend:
    image: a10d/pa_web1_backend
    build:
      context: backend
    ports:
      - "8080:8080"
    environment:
      - APP_INTERFACE=:8080